name: Vaultwarden
services:
  Vaultwarden:
    container_name: Vaultwarden
    image: vaultwarden/server:1.35.7@sha256:9a8eec71f4a52411cc43edc7a50f33e9b6f62b5baca0dd95f0c6e7fd60f1a341
    restart: unless-stopped
    networks:
      - Vaultwarden
    environment:
      - DOMAIN=${DOMAIN}
      - SIGNUPS_ALLOWED=false # Deactivate this with "false" after you have created your account so that no strangers can register (Although ideally you wouldn't expose your Vaultwarden instance to the outside world anyways)
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_TIMEOUT=${SMTP_TIMEOUT}
      - SMTP_SECURITY=${SMTP_SECURITY}
      - SMTP_PORT=${SMTP_PORT}
      - IP_HEADER=X-Forwarded-For # Trust the IP header from the reverse proxy
      - SENDS_ALLOWED=false # Deactivate sends -- My vault is only accessible on my home network so sends are not useful because others cannot access them.
    volumes:
      - ${DOCKER_VOLUMES}/Vaultwarden:/data/
      - /etc/localtime:/etc/localtime:ro

    user: "${UID}:${GID}"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    logging:
      driver: journald

    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 256M
          pids: 50

networks:
  Vaultwarden:
    name: Vaultwarden
    external: true
